### ISSUE TITLE
Use bundler config instead of deprecated flags

### ISSUE THREAD

**Issue by waghanza** [semaphoreci-demos/semaphore-demo-ruby-rails#14]
Hi Semaphore builders,

The flags `--deployment` and `--path` will fail CI in `ruby`  **>= 2.7**, the default bundler version will be `2.1`
@see https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

Using
```yaml
- bundle config set deployment 'true'
- bundle config set path 'vendor/bundle'
- bundle install
```
seems to be a working alternative to
https://github.com/semaphoreci-demos/semaphore-demo-ruby-rails/blob/c902df77b2043614df9756c3df41706e479c5b44/.semaphore/semaphore.yml#L74

Regards,

**Comment by markoa** [comment]
Thanks a lot for the tip. We'll update the example.

**Comment by AleksandarCole** [comment]
Updated with https://github.com/semaphoreci-demos/semaphore-demo-ruby-rails/pull/23
Closing this one.
